# Generated by Django 5.2.14 on 2026-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
